defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe


hydra:
  sweep:
    dir: multirun/${dataset}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    study_name: sphere
    storage: null
    n_trials: 20
    n_jobs: 1
    params:
      epoch: range(50,200,10)
      dim: range(80,240,40)
      gamma: tag(log, interval(1e-5,1e-2))




lr: 6e-3
epoch: 80
patch: 1
dim: 200
beta: 5e3
gamma: 3e-2
wdp: 4e-5
dataset: ???
